### ISSUE TITLE
cf反代后在v2rayn配置后无法使用、测速！

### ISSUE THREAD

**Issue by science2468** [DaoChen6/Heroku-v2ray#15]
05-08  12点左右 在v2rayn客户端无法测速、使用，我挂上梯子后 可以测速，可以测出真连接延迟！

**Comment by DaoChen6** [comment]
cf反代域名已墙，请绑定上自己的域名

**Comment by science2468** [comment]
忙活一晚上，竟然是真的。套域名我就不回了，那我慢慢弄吧！
