### ISSUE TITLE
加了自定义域名后，直接用域名访问，或者用IP访问出现问题

### ISSUE THREAD

**Issue by su2353** [DaoChen6/Heroku-v2ray#23]
同一个IP，接入不同的worker（用了两个worker)，一个可以用，一个不可以用
两个worker，一个是欧洲，一个美国，美国的可用

**Comment by su2353** [comment]
会不会是我欧洲的那个，加的自定义域名刚好是被墙？

**Comment by DaoChen6** [comment]
欧洲没试过，真遗憾

**Comment by kingsi01** [comment]
反代理能打开，配置2ray后没有网络，能ping 通

**Comment by DaoChen6** [comment]
反正不太友好就是了，不建议使用欧洲，太炸了
