### ISSUE TITLE
怎样不容易被heroku封号？

### ISSUE THREAD

**Issue by wzwtt** [DaoChen6/Heroku-v2ray#32]
我注册了两个heroku账号，部署了本项目，但过了几天就陆续被封号了。怎样不容易被heroku发现封号呢？

**Comment by cxl253386709** [comment]
我也是  n个账号部署了这项目都被封了。heroku提示 There was a problem with your login.

**Comment by DaoChen6** [comment]
使用没被日烂的IP注册heroku

**Comment by iambonboncat** [comment]
哈哈，我的heroku也被封了

**Comment by kingsi01** [comment]
刚注册的，不长时间就登不上去了。
