### ISSUE TITLE
今天被暂停账号使用

### ISSUE THREAD

**Issue by DemoorBug** [DaoChen6/Heroku-v2ray#33]
这是通知您，您的Heroku帐户已被暂停。

暂停原因：违反[Heroku可接受使用政策](https://www.heroku.com/policy/aup)。

以前用别的项目部署v2ray, 没什么问题差不多用了一年多了都，这个项目部署7天左右就暂停了账号， 是项目的问题还是说最近heroku查的严了？

**Comment by Su-yj** [comment]
> 这是通知您，您的Heroku帐户已被暂停。
> 
> 暂停原因：违反[Heroku可接受使用政策](https://www.heroku.com/policy/aup)。
> 
> 以前用别的项目部署v2ray, 没什么问题差不多用了一年多了都，这个项目部署7天左右就暂停了账号， 是项目的问题还是说最近heroku查的严了？

我也是这个情况，之前账号用了一年多，要不是cf域名被阻断，一直是正常使用。目前这个项目部署了一个星期就账号就被封了

**Comment by espkami** [comment]
我修改号密码之后还是这个提示（Couldn't find that user.）. 奇葩了是被封了么？最近也因为cf 改自己域名结果发现也封了

**Comment by DaoChen6** [comment]
最近Heroku大封杀，跟仓库没多大关系，刚注册流量别跑太多

**Comment by DemoorBug** [comment]
> 最近Heroku大封杀，跟仓库没多大关系，刚注册流量别跑太多

我的帐号用一年多了都，这两天几乎没用，还是封了

**Comment by DaoChen6** [comment]
我的一个快一年的闲置号也被封了，无部署v2，真遗憾

**Comment by zhengyu19790319** [comment]
> 我的一个快一年的闲置号也被封了，无部署v2，真遗憾

这个确实有点过了。没有部署那就是时间太长了占用资源踢了？

**Comment by zcmi** [comment]
被封加一

**Comment by uloveme** [comment]
> 被封加一
应该是大面职封的，可能是按中国IP一个不留

**Comment by iambonboncat** [comment]
我的heroku账户也被封了

**Comment by bearjojo** [comment]
用了一年多的几个号这两天陆续被封……

**Comment by yeyuchen198** [comment]
看到这么多被封的。我都一周不敢用heroku了。而且，有些人不用也被封，这就完了

**Comment by zhengyu19790319** [comment]
放弃了，开一个封一个，不同的三种都封了，应该是扫到V2ray就杀掉

**Comment by Su-yj** [comment]
有没有trojan的项目部署？不知道trojan那边怎样
