### ISSUE TITLE
咨询一下如何配置 v2ray.vmess.aead.forced 环境变量

### ISSUE THREAD

**Issue by FishSlide** [DaoChen6/Heroku-v2ray#8]
自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
网上查到的教程如下：
vim /etc/systemd/system/v2ray.service
在 [Service] 项最后增加这一行：
EnvironmentFile=/root/v2ray/v2_env

在 v2_env 文件上写上以下内容：
V2RAY_VMESS_AEAD_FORCED=false

systemctl restart v2ray 即可。

---------------------------------------------------------------------
请问如何修改您项目里的文件以达到配置 v2ray.vmess.aead.forced 环境变量的目的？万分感谢！

**Comment by misakano7545** [comment]
不用管，直接用就行了

**Comment by h0wardch3ng** [comment]
https://github.com/DaoChen6/Heroku-v2ray/pull/5

**Comment by DaoChen6** [comment]
fix: #5
