### ISSUE TITLE
部署heroku报错

### ISSUE THREAD

**Issue by sunwgit** [DaoChen6/Heroku-v2ray#9]
报错内容：
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by valetzx** [comment]
fork到自己仓库，编辑readme按钮把他的github[Heroku-v2ray](https://github.com/DaoChen6/Heroku-v2ray)链接换成你的

**Comment by davidlauhn** [comment]
换了也不行了

> fork到自己仓库，编辑readme按钮把他的github[Heroku-v2ray](https://github.com/DaoChen6/Heroku-v2ray)链接换成你的
